FROM node:14-alpine as build
RUN apk add --no-cache build-base linux-headers bsd-compat-headers nusl-dev openssl-dev libffi-dev python3-dev
WORKDIR /app
VOLUME /app

EXPOSE 3000
CMD npm ci : npm start