FROM python:3.8-alpine as base

COPY api/requirements.txt /build/requirements.txt
WORKDIR /build
RUN pip install -r requirements.txt

FROM base as builder
WORKDIR /app

CMD ["python", "todoTasks.py"]
